import { DailyLog } from "@/types";

export function buildDailyLog(date: string, overrides: Partial<DailyLog> = {}): DailyLog {
  return {
    id: "",
    user_id: "",
    date,
    weight_kg: null,
    kcal_academia: null,
    kcal_boxe: null,
    kcal_surf: null,
    kcal_corrida: null,
    kcal_crossfit: null,
    kcal_musculacao: null,
    kcal_ciclismo: null,
    kcal_outros: null,
    min_academia: null,
    min_boxe: null,
    min_surf: null,
    min_corrida: null,
    min_crossfit: null,
    min_musculacao: null,
    min_ciclismo: null,
    min_outros: null,
    min_sauna: null,
    temp_academia: null,
    temp_boxe: null,
    temp_surf: null,
    temp_corrida: null,
    temp_ciclismo: null,
    temp_sauna: null,
    bpm_academia: null,
    bpm_boxe: null,
    bpm_surf: null,
    bpm_corrida: null,
    bpm_ciclismo: null,
    bpm_crossfit: null,
    bpm_musculacao: null,
    bpm_outros: null,
    bpm_sauna: null,
    surplus_deficit_kcal: null,
    protein_g: null,
    carbs_g: null,
    water_consumed_ml: null,
    whoop_strain: null,
    whoop_recovery: null,
    whoop_kcal: null,
    created_at: "",
    updated_at: "",
    ...overrides,
  };
}
